version: '3'

services:
  spring_db:
    image: 'mysql:8'
    container_name: spring_db
    restart: always
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: web
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: webdb
    command: ['--default-authentication-plugin=mysql_native_password']
